USE LITTLELEMONDB;

DELIMITER //

CREATE PROCEDURE CheckBooking (IN DATEE DATE, IN TABLENR INT)
BEGIN
	DECLARE BOOKINGEXISTS INT;
	

	-- MIRAR SI HAY RESERVAS;
    SELECT COUNT(*) INTO BOOKINGEXISTS FROM BOOKINGS
    WHERE BOOKINGDATE=DATEE AND TABLENUMBER=TABLENR;
    
    -- CONDICION;
    IF BOOKINGEXISTS=0 THEN
		SELECT CONCAT('TABLE ',TABLENR, 'IS NOT BOOKED YET') AS 'BOOKING STATUS';
	ELSE
		SELECT CONCAT('TABLE ',TABLENR, ' IS ALREADY BOOKED') AS 'BOOKING STATUS';
    END IF;


END //

DELIMITER ;

CALL CheckBooking('2022-11-12',3);