USE LITTLELEMONDB;

SELECT CS.CUSTOMERID, CS.FULLNAME, OD.ORDERID, OD.TOTALCOST, MN.ITEMDESC, TY.TYPEDESC FROM CUSTOMERS AS CS
INNER JOIN ORDERS AS OD ON CS.CustomerID=OD.CustomerID
INNER JOIN MENU AS MN ON OD.ITEMID=MN.ITEMID
INNER JOIN TYPEMENU AS TY ON MN.TYPEID= TY.TYPEID
ORDER BY OD.TOTALCOST ASC;
